export const SET_START_OFFSET = "SET_START_OFFSET";
export const SET_BOARD_SIZE = "SET_BOARD_SIZE";
export const SET_ALIVE_TILES_AROUND_DEAD_TO_CREATE_LIFE = "SET_ALIVE_TILES_AROUND_DEAD_TO_CREATE_LIFE";
export const SET_ALIVE_TILES_AROUND_LIFE_TO_KEEP_LIFE = "SET_ALIVE_TILES_AROUND_LIVE_TO_KEEP_LIFE";